In [ ]:
#importing libraries 
import numpy as np
import pandas as pd

In [2]:
#reading cafes sales data 
df = pd.read_csv('/workspaces/data_cleaning_project/data/raw/Cafe Sales.csv')

In [3]:
df.head(10)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5,4.0,20.0,Credit Card,NaN,2023-03-31
6,TXN_4433211,UNKNOWN,3,3.0,9.0,ERROR,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4,4.0,16.0,Cash,UNKNOWN,2023-10-28
8,TXN_4717867,NaN,5,3.0,15.0,NaN,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5,4.0,20.0,NaN,In-store,2023-12-31

In [ ]:
df.info() # here most easy to handle is transaction date

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9667 non-null   str
 2   Quantity          9862 non-null   str
 3   Price Per Unit    9821 non-null   str
 4   Total Spent       9827 non-null   str
 5   Payment Method    7421 non-null   str
 6   Location          6735 non-null   str
 7   Transaction Date  9841 non-null   str
dtypes: str(8)
memory usage: 625.1 KB

In [6]:
#checking if there are any duplicates records or not
print(f'cafe sales data contains {sum(df.duplicated())} duplicate records')

cafe sales data contains 0 duplicate records

In [ ]:
#inspecting missing data from each column
df.isna().sum() * 100 / df.shape[0] #it will only  capture NaN values, not null or corrupts values like ERROR or Unknown

Transaction ID       0.00
Item                 3.33
Quantity             1.38
Price Per Unit       1.79
Total Spent          1.73
Payment Method      25.79
Location            32.65
Transaction Date     1.59
dtype: float64

In [ ]:
#inspecting uniques values in all columns other thand trasaction id as that has 0 null values
df_cols = set(df.columns) # changing the column in set as set exclude repetative values and only saves unique value
exclude = {'Transaction ID'} #creates a new set
df_cols = df_cols.difference(exclude) # excluding transaction id by comparing two sets and saving the data in df_cols
df_cols


for col in df_cols:
    print(f'{col}: \n{df[col].unique()}', end = '\n\n')

Price Per Unit:
<StringArray>
['2.0', '3.0', '1.0', '5.0', '4.0', '1.5', nan, 'ERROR', 'UNKNOWN']
Length: 9, dtype: str

Location:
<StringArray>
['Takeaway', 'In-store', 'UNKNOWN', nan, 'ERROR']
Length: 5, dtype: str

Transaction Date:
<StringArray>
['2023-09-08', '2023-05-16', '2023-07-19', '2023-04-27', '2023-06-11',
 '2023-03-31', '2023-10-06', '2023-10-28', '2023-07-28', '2023-12-31',
 ...
 '2023-08-01', '2023-01-20', '2023-11-11', '2023-02-13', '2023-07-30',
 '2023-02-17', '2023-05-20', '2023-11-05', '2023-03-27', '2023-07-03']
Length: 368, dtype: str

Total Spent:
<StringArray>
[    '4.0',    '12.0',   'ERROR',    '10.0',    '20.0',     '9.0',    '16.0',
    '15.0',    '25.0',     '8.0',     '5.0',     '3.0',     '6.0',       nan,
 'UNKNOWN',     '2.0',     '1.0',     '7.5',     '4.5',     '1.5']
Length: 20, dtype: str

Payment Method:
<StringArray>
['Credit Card', 'Cash', 'UNKNOWN', 'Digital Wallet', 'ERROR', nan]
Length: 6, dtype: str

Quantity:
<StringArray>
['2', '4', '5', '3', '1', 'ERROR', 'UNKNOWN', nan]
Length: 8, dtype: str

Item:
<StringArray>
[  'Coffee',     'Cake',   'Cookie',    'Salad', 'Smoothie',  'UNKNOWN',
 'Sandwich',        nan,    'ERROR',    'Juice',      'Tea']
Length: 11, dtype: str

In [ ]:
#replacing ERROR and UNKNOWN values with NaN
df = df.replace(['ERROR', 'UNKNOWN'],np.nan) # np.nan as it is related to numpy

In [13]:
df.head(10)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,NaN,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,NaN,NaN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5,4.0,20.0,Credit Card,NaN,2023-03-31
6,TXN_4433211,NaN,3,3.0,9.0,NaN,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4,4.0,16.0,Cash,NaN,2023-10-28
8,TXN_4717867,NaN,5,3.0,15.0,NaN,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5,4.0,20.0,NaN,In-store,2023-12-31

In [14]:
#changing data as int , float and date from str
df['Quantity'] = df['Quantity'].astype('Int64')
df[['Price Per Unit', 'Total Spent']] = df[['Price Per Unit', 'Total Spent']].astype('float')
df['Transaction Date'] = pd.to_datetime(df['Transaction Date'])

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9031 non-null   str
 2   Quantity          9521 non-null   Int64
 3   Price Per Unit    9467 non-null   float64
 4   Total Spent       9498 non-null   float64
 5   Payment Method    6822 non-null   str
 6   Location          6039 non-null   str
 7   Transaction Date  9540 non-null   datetime64[us]
dtypes: Int64(1), datetime64[us](1), float64(2), str(4)
memory usage: 634.9 KB

In [16]:
#inspecting missing data from each column after data treatment
df.isna().sum() * 100 / df.shape[0]

Transaction ID       0.00
Item                 9.69
Quantity             4.79
Price Per Unit       5.33
Total Spent          5.02
Payment Method      31.78
Location            39.61
Transaction Date     4.60
dtype: float64

In [17]:
#dropping records where transaction date is missing
df = df.dropna(subset =['Transaction Date'])

In [18]:
df.info()

<class 'pandas.DataFrame'>
Index: 9540 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    9540 non-null   str
 1   Item              8613 non-null   str
 2   Quantity          9086 non-null   Int64
 3   Price Per Unit    9034 non-null   float64
 4   Total Spent       9064 non-null   float64
 5   Payment Method    6525 non-null   str
 6   Location          5761 non-null   str
 7   Transaction Date  9540 non-null   datetime64[us]
dtypes: Int64(1), datetime64[us](1), float64(2), str(4)
memory usage: 680.1 KB

In [21]:
#transaction_date is 0
df.isna().sum() * 100 / df.shape[0]

Transaction ID       0.000000
Item                 9.716981
Quantity             4.758910
Price Per Unit       5.303983
Total Spent          4.989518
Payment Method      31.603774
Location            39.612159
Transaction Date     0.000000
dtype: float64

In [23]:
#replacing values in payment method and location with INA(info not vaailable)
#dropping these high volume of records will lead to significant data loss
#inputing INA avoid bias
df[['Payment Method','Location']] = df[['Payment Method','Location']].fillna('INA')

In [26]:
# null data is replaced with ina not null datat for payment method and location
df.isna().sum() * 100 / df.shape[0]

Transaction ID      0.000000
Item                9.716981
Quantity            4.758910
Price Per Unit      5.303983
Total Spent         4.989518
Payment Method      0.000000
Location            0.000000
Transaction Date    0.000000
dtype: float64

In [28]:
#inspecting mean and median values for quantity
quantity_mean , quantity_median = round(df['Quantity'].mean() , 0) , round(df['Quantity'].median() , 0)

print(f'mean : {quantity_mean} & median : {quantity_median}')

mean : 3.0 & median : 3.0

In [ ]:
# since both are similar replacing missing values with mean values...median is better to use here both same so does not matter
df['Quantity'] = df['Quantity'].fillna(quantity_mean)

In [ ]:
# null data is replaced with mean values for quantity
df.isna().sum() * 100 / df.shape[0]

Transaction ID      0.000000
Item                9.716981
Quantity            0.000000
Price Per Unit      5.303983
Total Spent         4.989518
Payment Method      0.000000
Location            0.000000
Transaction Date    0.000000
dtype: float64

In [ ]:
# replacing missing values in Item with mode value, or 0 index value
df['Item'] = df['Item'].fillna(df['Item'].mode()[0])

In [ ]:
#null data of items are replaced
df.isna().sum() * 100 / df.shape[0]

Transaction ID      0.000000
Item                0.000000
Quantity            0.000000
Price Per Unit      5.303983
Total Spent         4.989518
Payment Method      0.000000
Location            0.000000
Transaction Date    0.000000
dtype: float64

In [33]:
# checking how many distinct prices exist for each Item category and how many times each price point is registered.
df.groupby('Item')['Price Per Unit'].value_counts()

Item      Price Per Unit
Cake      3.0               1031
Coffee    2.0               1069
Cookie    1.0                976
Juice     3.0               1288
          4.0                202
          2.0                116
          5.0                115
          1.0                112
          1.5                108
Salad     5.0               1035
Sandwich  4.0               1027
Smoothie  4.0                990
Tea       1.5                965
Name: count, dtype: int64

In [35]:
 #filling missing Price Per Unit values with the most frequent (mode) price for each Item category
 df['Price Per Unit'] = df.groupby('Item')['Price Per Unit'].transform(lambda x: x.fillna(x.mode()[0]))

In [ ]:
#removed null data of price per unit by replacing the data with mode value
df.isna().sum() * 100 / df.shape[0]

Transaction ID      0.000000
Item                0.000000
Quantity            0.000000
Price Per Unit      0.000000
Total Spent         4.989518
Payment Method      0.000000
Location            0.000000
Transaction Date    0.000000
dtype: float64

In [37]:
# filling missing records for Total Spent by calculating the product of Quantity times Price Per Unit
df['Total Spent'] = df['Total Spent'].fillna(df['Quantity'] * df['Price Per Unit'])

In [38]:
#all data are cleaaned data
df.isna().sum() * 100 / df.shape[0]

Transaction ID      0.0
Item                0.0
Quantity            0.0
Price Per Unit      0.0
Total Spent         0.0
Payment Method      0.0
Location            0.0
Transaction Date    0.0
dtype: float64

In [39]:
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,4.0,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,INA,INA,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [40]:
#storing clean data
df.to_csv('/workspaces/data_cleaning_project/data/clean/cafesales_clean.csv', index = False)